name: Build and Release Flutter APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11' # Use Java 11 for better compatibility with Flutter and Gradle

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Upload APK to GitHub Releases
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          tag: v${{ github.run_number }} # Use the workflow run number for dynamic versioning
          name: Release v${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
